# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(984, 776)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setStyleSheet("qproperty-alignment: AlignCenter;")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 3, 1, 1)
        self.open_word_dir = QtWidgets.QPushButton(self.tab)
        self.open_word_dir.setObjectName("open_word_dir")
        self.gridLayout_3.addWidget(self.open_word_dir, 0, 0, 1, 2)
        self.run_transformation = QtWidgets.QPushButton(self.tab)
        self.run_transformation.setStyleSheet("margin-bottom: 50px;\n"
"margin-top: 20px;\n"
"padding: 5px;")
        self.run_transformation.setObjectName("run_transformation")
        self.gridLayout_3.addWidget(self.run_transformation, 1, 0, 1, 1)
        self.prepend_text_edit = QtWidgets.QPlainTextEdit(self.tab)
        self.prepend_text_edit.setMaximumSize(QtCore.QSize(100, 25))
        self.prepend_text_edit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.prepend_text_edit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.prepend_text_edit.setObjectName("prepend_text_edit")
        self.gridLayout_3.addWidget(self.prepend_text_edit, 0, 4, 1, 1)
        self.open_output_dir = QtWidgets.QPushButton(self.tab)
        self.open_output_dir.setObjectName("open_output_dir")
        self.gridLayout_3.addWidget(self.open_output_dir, 0, 2, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_3.addWidget(self.textEdit, 3, 0, 1, 6)
        self.open_word_dir.raise_()
        self.open_output_dir.raise_()
        self.label.raise_()
        self.textEdit.raise_()
        self.prepend_text_edit.raise_()
        self.run_transformation.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.directory = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        self.directory.setFont(font)
        self.directory.setText("")
        self.directory.setObjectName("directory")
        self.gridLayout_2.addWidget(self.directory, 0, 0, 1, 2)
        self.results = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        self.results.setFont(font)
        self.results.setStyleSheet("margin-top: 25px;\n"
"margin-bottom: 5px;")
        self.results.setObjectName("results")
        self.gridLayout_2.addWidget(self.results, 6, 0, 1, 1)
        self.dir_open = QtWidgets.QPushButton(self.tab2)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(13)
        self.dir_open.setFont(font)
        self.dir_open.setObjectName("dir_open")
        self.gridLayout_2.addWidget(self.dir_open, 3, 0, 1, 1)
        self.list_widget = QtWidgets.QListWidget(self.tab2)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(17)
        self.list_widget.setFont(font)
        self.list_widget.setObjectName("list_widget")
        self.gridLayout_2.addWidget(self.list_widget, 7, 0, 1, 3)
        self.export_2 = QtWidgets.QPushButton(self.tab2)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(13)
        self.export_2.setFont(font)
        self.export_2.setObjectName("export_2")
        self.gridLayout_2.addWidget(self.export_2, 8, 2, 1, 1)
        self.check_box = QtWidgets.QCheckBox(self.tab2)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        self.check_box.setFont(font)
        self.check_box.setObjectName("check_box")
        self.gridLayout_2.addWidget(self.check_box, 3, 1, 1, 1)
        self.run_report = QtWidgets.QPushButton(self.tab2)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        self.run_report.setFont(font)
        self.run_report.setStyleSheet("")
        self.run_report.setObjectName("run_report")
        self.gridLayout_2.addWidget(self.run_report, 4, 0, 1, 1)
        # self.tabWidget.addTab(self.tab2, "")
        self.gridLayout.addWidget(self.tabWidget, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 984, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>QC Tool</p></body></html>"))
        self.label.setText(_translate("MainWindow", "prepend text"))
        self.open_word_dir.setText(_translate("MainWindow", "open docx directory"))
        self.run_transformation.setText(_translate("MainWindow", "run transformation"))
        self.open_output_dir.setText(_translate("MainWindow", "set output"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Docx2TEI"))
        self.results.setText(_translate("MainWindow", "Results:"))
        self.dir_open.setText(_translate("MainWindow", "open directory"))
        self.export_2.setText(_translate("MainWindow", "export report"))
        self.check_box.setText(_translate("MainWindow", "Fix Errors"))
        self.run_report.setText(_translate("MainWindow", "run report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "QC Tool"))

